# Generated by Django 4.1.7 on 2023-03-27 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 18, 50, 42, 539277, tzinfo=datetime.timezone.utc)),
        ),
    ]
