# Generated by Django 4.1.7 on 2023-03-27 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_profiletask_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 18, 50, 48, 752230, tzinfo=datetime.timezone.utc)),
        ),
    ]
