# Generated by Django 4.1.7 on 2023-03-27 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_profiletask_dead_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='profile_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.profiletask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 20, 8, 9, 858548, tzinfo=datetime.timezone.utc)),
        ),
    ]
