# Generated by Django 4.1.7 on 2023-03-27 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_filemodel_user_filemodel_profile_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='success',
        ),
        migrations.AddField(
            model_name='profiletask',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 20, 12, 3, 529135, tzinfo=datetime.timezone.utc)),
        ),
    ]
